version: '3'

services:
  database:
    env_file: .env
    container_name: friend_finder_postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      restart: always
    ports:
      - "6543:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

#  bot:
#    container_name: $BOT_CONTAINER_NAME
#    build: .
#    volumes:
#      - .:/src
#    restart: always
#    depends_on:
#      - database

