version: '3'

services:
  database:
    env_file: .env
    container_name: $DB_BOT_CONTAINER_NAME
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      restart: always
    ports:
      - "6543:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  bot:
    container_name: $BOT_CONTAINER_NAME
    build: .
    volumes:
      - .:/src
    restart: always
    depends_on:
      - database

